permissions:
  contents: write    # 允许推送回仓库

name: 每日更新 EasyList 规则

on:
  schedule:
    - cron: '0 17 * * *'    # 每天 17:00 UTC（北京时间次日 01:00）触发
  workflow_dispatch:       # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: 安装依赖
        run: |
          python3 -m pip install --upgrade pip requests

      - name: 转换规则
        run: python3 convert_rules.py

      - name: 提交并推送更新
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/rules.txt
          git commit -m "自动更新 rules.txt ($(date -u +'%Y-%m-%d'))" || echo "no changes"
          git push
